version: '3.8'

services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-front-innovatech
    ports:
      - "80:5000"
    environment:
      - BACKEND_URL=http://10.0.2.85:8000 
      - PORT=5000
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    networks:
      - innovatech-net

networks:
  innovatech-net:
    driver: bridge