version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-front-innovatech
    ports:
      - "80:5000"
    environment:
      # CAMBIO: Ahora puedes usar el nombre del servicio 'backend' en vez de la IP rígida
      - BACKEND_URL=http://100.55.48.50:8000
      - PORT=5000
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - vpc_front_logs:/app/logs
    restart: always
    networks:
      # Conectamos el contenedor a la red externa del backend
      - backend_innovatech-net

# Bloque único de networks al final del archivo
networks:
  backend_innovatech-net:
    external: true
