version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-front-innovatech
    ports:
      - "80:5000"
    environment:
      BACKEND_URL: "http://44.198.58.197:3000"
      PORT: 5000
      DEBUG: "False"
      SECRET_KEY: "${SECRET_KEY}" 
    volumes:
      - vpc_front_logs:/app/logs
    restart: always
    networks:
      - backend_innovatech-net

volumes:
  vpc_front_logs:

networks:
  backend_innovatech-net:
    driver: bridge