name: Deploy Frontend

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy Frontend via Docker Compose
        run: |
          cd ~/innovatech-chile
          cp -r ${{ github.workspace }}/* .
          docker compose up -d --build frontend